import {
  ArrowUpDown,
  Briefcase,
  GitBranch,
  Image as ImageIcon,
  Layers,
  Mail,
  PanelBottom,
  Settings,
  User,
} from "lucide-react";

import type { SectionConfig } from "@/lib/admin/types";

export const SECTION_CONFIGS: SectionConfig[] = [
  {
    title: "Section Builder",
    section: "section_order",
    mode: "collection",
    icon: <ArrowUpDown size={18} />,
    description: "Rearrange homepage section order with drag and drop.",
    fields: [
      { key: "title", label: "Title", type: "text" },
      { key: "section_key", label: "Section Key", type: "text" },
      { key: "sort_order", label: "Sort Order", type: "number" },
    ],
  },
  {
    title: "Hero",
    section: "hero",
    mode: "single",
    icon: <ImageIcon size={18} />,
    description: "Main hero banner - heading, desktop/mobile background images, and name label.",
    fields: [
      { key: "heading", label: "Heading", type: "textarea", placeholder: "Main hero heading text" },
      { key: "background_image_url", label: "Desktop Background Image", type: "image" },
      { key: "mobile_background_image_url", label: "Mobile Background Image", type: "image" },
      { key: "name_label", label: "Name Label", type: "text", placeholder: "e.g. TALHA IRFAN" },
    ],
  },
  {
    title: "About",
    section: "about",
    mode: "single",
    icon: <User size={18} />,
    description: "Bio section - heading, description text, and statistics.",
    fields: [
      { key: "label", label: "Section Label", type: "text", placeholder: "e.g. [ WHO I AM ]" },
      { key: "heading", label: "Heading", type: "textarea", placeholder: "About section heading" },
      { key: "description", label: "Description", type: "textarea", placeholder: "About description paragraph" },
      {
        key: "stats",
        label: "Stats",
        type: "stats",
        description: "Each stat has a value, suffix, and label.",
      },
    ],
  },
  {
    title: "Why Choose Us",
    section: "why_choose_us",
    mode: "single",
    icon: <ImageIcon size={18} />,
    description: "Studio value proposition - stats, testimonials, and scale info.",
    fields: [
      { key: "label", label: "Section Label", type: "text", placeholder: "[ WHY CHOOSE US ]" },
      { key: "heading", label: "Heading", type: "textarea" },
      { key: "studio_name", label: "Studio Name", type: "text" },
      { key: "studio_image_url", label: "Studio Image", type: "image" },
      { key: "studio_since", label: "Since Label", type: "text" },
      { key: "testimonial_text", label: "Testimonial", type: "textarea" },
      { key: "revenue_stat", label: "Revenue Stat", type: "text" },
      { key: "revenue_label", label: "Revenue Label", type: "text" },
      { key: "scale_stat", label: "Scale Stat", type: "text" },
      { key: "scale_description", label: "Scale Description", type: "textarea" },
    ],
  },
  {
    title: "Works",
    section: "works",
    mode: "collection",
    icon: <Briefcase size={18} />,
    description: "Portfolio project cards and detail page content.",
    fields: [
      { key: "title", label: "Project Title", type: "text", placeholder: "Project name" },
      { key: "client", label: "Client", type: "text", placeholder: "Client or category" },
      { key: "summary", label: "Project Summary", type: "textarea", placeholder: "Short project story shown on detail page" },
      { key: "project_url", label: "Live Project URL", type: "text", placeholder: "https://example.com" },
      { key: "image_url", label: "Main Image", type: "image" },
      { key: "hover_image_url", label: "Hover Image", type: "image" },
      { key: "gallery_images", label: "Detail Gallery Images", type: "image-list" },
      { key: "sort_order", label: "Sort Order", type: "number" },
    ],
    createDefaults: {
      title: "",
      client: "",
      summary: "",
      project_url: "",
      image_url: "",
      hover_image_url: "",
      gallery_images: [],
      sort_order: 0,
    },
  },
  {
    title: "Works Section",
    section: "works_meta",
    mode: "single",
    icon: <Settings size={18} />,
    description: "Homepage/archive works section labels and display limits.",
    fields: [
      { key: "homepage_label", label: "Homepage Label", type: "text", placeholder: "[ FEATURED PROJECTS ]" },
      { key: "homepage_heading", label: "Homepage Heading", type: "text", placeholder: "Works." },
      { key: "featured_count", label: "Homepage Featured Count", type: "number" },
      { key: "archive_heading", label: "Archive Page Heading", type: "text", placeholder: "Archive." },
    ],
  },
  {
    title: "Services",
    section: "services",
    mode: "collection",
    icon: <Layers size={18} />,
    description: "Service accordion items with tags and gallery images.",
    fields: [
      { key: "title", label: "Service Title", type: "text", placeholder: "Service name" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Service description" },
      { key: "tags", label: "Tags", type: "string-list", placeholder: "UI/UX Design" },
      { key: "images", label: "Images", type: "image-list" },
      { key: "sort_order", label: "Sort Order", type: "number" },
    ],
    createDefaults: { title: "", description: "", tags: [], images: [], sort_order: 0 },
  },
  {
    title: "Services Section",
    section: "services_meta",
    mode: "single",
    icon: <Settings size={18} />,
    description: "Services section hero content, side image, and CTA.",
    fields: [
      { key: "label", label: "Section Label", type: "text", placeholder: "[ OUR SERVICES ]" },
      { key: "profile_image_url", label: "Profile Image", type: "image" },
      { key: "intro_text", label: "Intro Text", type: "textarea", placeholder: "Short intro copy" },
      { key: "cta_text", label: "CTA Text", type: "text", placeholder: "Start a project" },
      { key: "cta_url", label: "CTA Link", type: "text", placeholder: "#contact" },
    ],
  },
  {
    title: "Process",
    section: "process_steps",
    mode: "collection",
    icon: <GitBranch size={18} />,
    description: "Step-by-step process cards displayed on the site.",
    fields: [
      { key: "number", label: "Step Number", type: "text", placeholder: "[ 01 ]" },
      { key: "title", label: "Title", type: "text", placeholder: "Step title" },
      { key: "description", label: "Description", type: "textarea", placeholder: "Step description" },
      { key: "sort_order", label: "Sort Order", type: "number" },
    ],
    createDefaults: { number: "", title: "", description: "", sort_order: 0 },
  },
  {
    title: "Process Section",
    section: "process_meta",
    mode: "single",
    icon: <Settings size={18} />,
    description: "Process section headline label settings.",
    fields: [{ key: "label", label: "Section Label", type: "text", placeholder: "[ OUR PROCESS ]" }],
  },
  {
    title: "Reach Us",
    section: "reachus",
    mode: "single",
    icon: <Mail size={18} />,
    description: "Contact section - headline, email, and social links.",
    fields: [
      { key: "label", label: "Section Label", type: "text", placeholder: "[ REACH US ]" },
      { key: "heading", label: "Heading", type: "textarea", placeholder: "Contact heading" },
      { key: "email", label: "Email", type: "text", placeholder: "hello@example.com" },
      { key: "office_title", label: "Office Block Title", type: "text", placeholder: "OFFICE" },
      { key: "office_line_1", label: "Office Line 1", type: "text", placeholder: "Available Worldwide" },
      { key: "office_line_2", label: "Office Line 2", type: "text", placeholder: "Working Remotely" },
      { key: "office_line_3", label: "Office Line 3", type: "text", placeholder: "Based in PK" },
      { key: "inquiry_title", label: "Inquiry Block Title", type: "text", placeholder: "INQUIRIES" },
      { key: "inquiry_text", label: "Inquiry Text", type: "textarea", placeholder: "For new projects and partnership questions:" },
      {
        key: "socials",
        label: "Social Links",
        type: "socials",
        description: "Manage social platform links as structured rows.",
      },
    ],
  },
  {
    title: "Footer",
    section: "footer",
    mode: "single",
    icon: <PanelBottom size={18} />,
    description: "Newsletter section and footer brand identity.",
    fields: [
      { key: "newsletter_heading", label: "Newsletter Heading", type: "text", placeholder: "Stay connected" },
      { key: "newsletter_description", label: "Newsletter Description", type: "textarea" },
      { key: "brand_name", label: "Brand Name", type: "text", placeholder: "TALHA" },
      { key: "email", label: "Email", type: "text", placeholder: "hello@example.com" },
    ],
  },
];
